componentName: payment
appPort: 8080
appVersion: 3.0.2
externalSecret:
  enabled: true
resources:
   limits:
     cpu: 1600m
     memory: 1500Mi
   requests:
     cpu: 16000m
     memory: 1500Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
healthEndpoint: /health
